version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: {  interval: "daily" }
    labels: [ "Dependencies", "Automation" ]
    reviewers: [ "rdeago" ]
  - package-ecosystem: "nuget"
    directory: "/"
    schedule: {  interval: "daily" }
    labels: [ "Dependencies" ]
    reviewers: [ "rdeago" ]
