area-ci:
  - any: ['.github/workflows/**/*']

area-deps:
  - any: ['**/PackageVersions.props', 'Directory.Build.props', 'Directory.Build.targets']

area-docs:
  - any: ['.github/**/*', '**/LICENSE', '**/README.md', '**/THIRD-PARTY-NOTICES']

area-repo:
  - any: ['.github/*.yml', '.github/**/*.md']
