area-ci:
  - ".github/workflows/**/*"

area-deps:
  - "**/PackageVersions.props"
  - Directory.Build.props
  - Directory.Build.targets

area-docs:
  - ".github/**/*"
  - "**/LICENSE"
  - "**/README.md"
  - "**/THIRD-PARTY-NOTICES"

area-repo:
  - ".github/*.yml"
  - ".github/**/*.md"
