area-code:
  - "**/*.cs"

area-build:
  - "**/*.csproj"
  - "**/Common.props"
  - "**/Common.targets"

area-ci:
  - ".github/workflows/**/*"
  - lgtm.yml

area-deps:
  - "**/Directory.Packages.props"
  - Directory.Build.props
  - Directory.Build.targets

area-docs:
  - "docs/**/*"
  - "**/LICENSE"
  - "**/README.md"
  - "**/THIRD-PARTY-NOTICES"

area-repo:
  - ".github/*.yml"
  - ".github/**/*.md"
