name: Continuous integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ContinuousIntegrationBuild: "true"
  DOTNET_NOLOGO: "true"

jobs:

  test:
    name: Unit testing and code coverage reporting
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        net: [ 3.1.x, 5.0.x ]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET ${{ matrix.net }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.net }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build -c Release --no-restore -maxCpuCount:1

    - name: Run unit tests, collect code coverage information
      run: dotnet test -c Release --no-build -p:CollectCoverage=true -p:CoverletOutput="${{ github.workspace }}/.coverage/lcov_${{ matrix.os }}_${{ matrix.net }}.info" -p:CoverletOutputFormat=lcov

    - name: Create .NET local tool manifest file
      run: dotnet new tool-manifest

    - name: Install Codecov tool
      run: dotnet tool install Codecov.Tool

    - name: Upload coverage reports
      run: dotnet tool run codecov -f .coverage/lcov_${{ matrix.os }}_${{ matrix.net }}.info --no-color --required

    - name: Generate packages
      run: dotnet pack -c Release --no-build
