name: Continuous integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ContinuousIntegrationBuild: "true"

jobs:

  test:
    name: Unit testing and code coverage reporting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.0
      with:
        dotnet-version: 3.1.x
    - name: Configure access to GitHub Packages
      run: dotnet nuget update source Buildvana -u ${{ github.repository_owner }} -p ${{ github.token }} --store-password-in-clear-text
    - name: Run unit tests, collect code coverage information
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutput="${{ github.workspace }}/.coverage/lcov-${{ matrix.os }}.info" /p:CoverletOutputFormat=lcov -c Release
    - name: Create .NET local tool manifest file
      run: dotnet new tool-manifest
    - name: Install Codecov tool
      run: dotnet tool install Codecov.Tool
    - name: Upload coverage reports
      run: dotnet tool run codecov -f .coverage/lcov-${{ matrix.os }}.info --no-color --required
